version: '3.8'

services:
  docmod-bff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docmod-bff
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - docmod-data:/app
    networks:
      - docmod-network

  nginx:
    image: nginx:alpine
    container_name: docmod-nginx
    ports:
      - "81:80"
    restart: unless-stopped
    command: >
      sh -c " cat > /etc/nginx/nginx.conf << 'EOF' events {
          worker_connections 1024;
      } http {
          include /etc/nginx/mime.types;
          default_type application/octet-stream;
          
          upstream docmod_backend {
              server docmod-bff:3000;
          }
          server {
              listen 80;
              server_name localhost;
              location /api/ {
                  proxy_pass http://docmod_backend/;
                  proxy_set_header Host \$$host;
                  proxy_set_header X-Real-IP \$$remote_addr;
                  proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$$scheme;
                  add_header Access-Control-Allow-Origin *;
                  add_header Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS\";
                  add_header Access-Control-Allow-Headers \"Content-Type, Authorization\";
                  if (\$$request_method = OPTIONS) {
                      return 200;
                  }
              }
              location /view/ {
                  alias /app/;
                  index index.html;
                  try_files \$$uri \$$uri/ \$$uri/index.html =404;
              }
              location ~ ^/view/([^/]+)/?(.*)$ {
                  alias /app/\$$1/.vitepress/dist/;
                  index index.html;
                  try_files \$$2 \$$2/ \$$2/index.html /index.html =404;
              }
              location ~ ^/view/([^/]+)/assets/(.*)$ {
                  alias /app/\$$1/.vitepress/dist/assets/\$$2;
              }
              location = / {
                  return 301 /view/;
              }
              error_page 404 /404.html;
              location = /404.html {
                  root /usr/share/nginx/html;
                  internal;
              }
              error_page 500 502 503 504 /50x.html;
              location = /50x.html {
                  root /usr/share/nginx/html;
                  internal;
              }
          }
      } EOF && nginx -g 'daemon off;' "
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - docmod-data:/app
    networks:
      - docmod-network
    depends_on:
      - docmod-bff
volumes:
  docmod-data:
    driver: local

networks:
  docmod-network:
    driver: bridge
