version: '3.8'

services:
  docmod-bff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docmod-bff
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - docmod-data:/app
    networks:
      - docmod-network

  nginx:
    image: nginx:alpine
    container_name: docmod-nginx
    ports:
      - "81:80"
    restart: unless-stopped
    volumes:
      - ./nginx_custom.conf:/etc/nginx/nginx_custom.conf
      - ./html:/usr/share/nginx/html
      - docmod-data:/app
    networks:
      - docmod-network
    depends_on:
      - docmod-bff
volumes:
  docmod-data:
    driver: local

networks:
  docmod-network:
    driver: bridge
