version: '3.8'

services:
  docmod-bff:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true # Force rebuild mỗi lần
    container_name: docmod-bff
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - docmod-data:/app
    networks:
      - docmod-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      no_cache: true # Force rebuild mỗi lần
    container_name: docmod-nginx
    expose:
      - 80
    restart: unless-stopped
    volumes:
      - docmod-data:/app
    networks:
      - docmod-network
    depends_on:
      - docmod-bff
volumes:
  docmod-data:
    driver: local

networks:
  docmod-network:
    driver: bridge
